export const columns = [
  "Advertiser",
  "email_message_id",
  "Date",
  "JobGroup",
  "JobId",
  "Name",
  "Email",
  "PhoneNumber",
  "Location",
  "Role",
  "ResumeLink",
  "Campaign",
  "JobLocation",
  "SubmissionStatus",
  "Submission_Email_Sent",
  "Good to submit?",
  "Owner",
  "Source",
  "QualityCheck",
  "Quality Rechecked",
  "LocationCheck",
  "Duplicate",
  "Why not Good ?",
  "Notes",
  "Consent ?",
  "Alternative email ?",
  "Name Matches Resume?",
  "Number Matches Resume?",
  "Email Matches Resumes?",
  "Location Matches Resume?",
  "Trigger",
  "Status (Output)"
];

export const data = [
  [
    "Aveanna",
    "a02d84a41ad4a8b8",
    "11/6",
    "Group-ab1f",
    "JOB-346e43",
    "Robert Thomas",
    "robert.thomas11@gmail.com",
    "+18445406296",
    "Dallas, OH",
    "LPN/LVN",
    "https://drive.google.com/file/d/5ba451d001d7135cf5d1/view?usp=drive_link",
    "Texas",
    "Dallas, OH",
    "Pending",
    "Yes",
    "No",
    "Vaishnavi",
    "Manatal",
    "Average",
    "Yes",
    "Match",
    "No",
    "Skills",
    "Notes for candidate 0",
    "Yes",
    "Rthomas@outlook.com",
    "TRUE",
    "FALSE",
    "TRUE",
    "TRUE",
    "Email",
    "Failed"
  ],
  [
    "Aveanna",
    "1c4f03454b3c0ff3",
    "11/7",
    "Group-8fef",
    "JOB-4ef677",
    "Barbara Garcia",
    "barbara.garcia84@gmail.com",
    "+18575841233",
    "Dallas, FL",
    "LPN/LVN",
    "https://drive.google.com/file/d/f5be910dd17ea1cfd531/view?usp=drive_link",
    "Texas",
    "Dallas, FL",
    "Submitted",
    null,
    "Yes",
    "Ishan",
    "ZipOrg",
    "Good",
    null,
    "Match",
    "Yes",
    null,
    "Notes for candidate 1",
    "No",
    null,
    "FALSE",
    "FALSE",
    "TRUE",
    "FALSE",
    "Email",
    "Failed"
  ],
  [
    "Aveanna",
    "53c6c6ba2921d730",
    "11/8",
    "Group-0593",
    "JOB-047cfb",
    "Robert Brown",
    "robert.brown57@gmail.com",
    "+16270888136",
    "Dallas, TX",
    "Registered Nurse",
    "https://drive.google.com/file/d/70318705c10d06348a98/view?usp=drive_link",
    "Texas",
    "Dallas, TX",
    "Interview",
    "No",
    "Yes",
    "Vaishnavi",
    "ZipOrg",
    "Good",
    "No",
    "No Match",
    "Yes",
    "Location",
    "Notes for candidate 2",
    "Yes",
    null,
    "TRUE",
    "FALSE",
    "TRUE",
    "TRUE",
    null,
    null
  ],
  [
    "Aveanna",
    "e5891e61f57bcf7a",
    "11/9",
    "Group-2bb2",
    "JOB-98729e",
    "Margaret Williams",
    "margaret.williams36@gmail.com",
    "+17880146924",
    "Arlington, IL",
    "Registered Nurse",
    "https://drive.google.com/file/d/53e134593df1e4950a44/view?usp=drive_link",
    "Texas",
    "Arlington, IL",
    null,
    "Yes",
    "Maybe",
    "Vaishnavi",
    "ZipSp",
    "Bad",
    "No",
    "Match",
    null,
    "Location",
    "Notes for candidate 3",
    "No",
    null,
    "TRUE",
    "FALSE",
    "TRUE",
    "FALSE",
    "SMS",
    null
  ],
  [
    "Aveanna",
    "84200664b47c2573",
    "11/10",
    "Group-6104",
    "JOB-693a41",
    "Ashley Rodriguez",
    "ashley.rodriguez73@gmail.com",
    "+14855627440",
    "Fort Worth, GA",
    "Registered Nurse",
    "https://drive.google.com/file/d/ef2901bd09f3aa1f9a38/view?usp=drive_link",
    "Texas",
    "Fort Worth, GA",
    null,
    "No",
    "Maybe",
    "Nitin",
    "ZipOrg",
    "Average",
    null,
    "No Match",
    "Yes",
    null,
    "Notes for candidate 4",
    "Yes",
    "Arodriguez@outlook.com",
    "TRUE",
    "TRUE",
    "FALSE",
    "FALSE",
    "Email",
    "Failed"
  ],
  [
    "Aveanna",
    "a4327666808dec82",
    "11/11",
    "Group-d13d",
    "JOB-4c2cab",
    "Barbara Taylor",
    "barbara.taylor6@gmail.com",
    "+16954771943",
    "Austin, MI",
    "Registered Nurse",
    "https://drive.google.com/file/d/86aa996dc1a0a0447b5b/view?usp=drive_link",
    "Texas",
    "Austin, MI",
    "Interview",
    "Yes",
    null,
    "Vaishnavi",
    "ZipOrg",
    "Average",
    null,
    "Match",
    "No",
    "Experience",
    "Notes for candidate 5",
    "Yes",
    null,
    "TRUE",
    "TRUE",
    "TRUE",
    "TRUE",
    null,
    "Failed"
  ],
  [
    "Aveanna",
    "e0dacd62a7489ba7",
    "11/12",
    "Group-6ff8",
    "JOB-16c799",
    "James Taylor",
    "james.taylor73@gmail.com",
    "+18738406719",
    "Dallas, FL",
    "LPN/LVN",
    "https://drive.google.com/file/d/c6bd9ba2c55a58682153/view?usp=drive_link",
    "Texas",
    "Dallas, FL",
    "Rejected",
    "Yes",
    "No",
    "Shivam",
    "ZipSp",
    "Bad",
    "No",
    "No Match",
    "No",
    "Skills",
    "Notes for candidate 6",
    "No",
    "Jtaylor@outlook.com",
    "TRUE",
    "TRUE",
    "TRUE",
    "FALSE",
    "Email",
    null
  ],
  [
    "Aveanna",
    "d0da191c50a94086",
    "11/13",
    "Group-497c",
    "JOB-24907b",
    "David Garcia",
    "david.garcia46@gmail.com",
    "+12404446389",
    "El Paso, OH",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/1bc2e3c6e15366140515/view?usp=drive_link",
    "Texas",
    "El Paso, OH",
    "Submitted",
    "Yes",
    "Maybe",
    "Vaishnavi",
    "ZipOrg",
    "Good",
    null,
    "Match",
    null,
    "Experience",
    "Notes for candidate 7",
    "Yes",
    "Dgarcia@outlook.com",
    "TRUE",
    "FALSE",
    "TRUE",
    "FALSE",
    null,
    null
  ],
  [
    "Aveanna",
    "babdf9963b7a59e8",
    "11/14",
    "Group-874e",
    "JOB-6b08bd",
    "Margaret Davis",
    "margaret.davis52@gmail.com",
    "+13331714218",
    "El Paso, FL",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/6166266419b1a1ead7f4/view?usp=drive_link",
    "Texas",
    "El Paso, FL",
    null,
    "No",
    null,
    "Shivam",
    "Manatal",
    "Average",
    "Yes",
    "No Match",
    "Yes",
    "Location",
    "Notes for candidate 8",
    "No",
    "Mdavis@outlook.com",
    "FALSE",
    "TRUE",
    "FALSE",
    "TRUE",
    "SMS",
    null
  ],
  [
    "Aveanna",
    "49cd89e8abe74eaf",
    "11/15",
    "Group-2ac8",
    "JOB-854ae9",
    "James Moore",
    "james.moore45@gmail.com",
    "+12353495636",
    "Dallas, MI",
    "Registered Nurse",
    "https://drive.google.com/file/d/09dc9b6765ec814d3a92/view?usp=drive_link",
    "Texas",
    "Dallas, MI",
    "Rejected",
    null,
    "No",
    "Vaishnavi",
    "Manatal",
    "Average",
    "Yes",
    "Match",
    null,
    null,
    "Notes for candidate 9",
    "No",
    null,
    "TRUE",
    "FALSE",
    "FALSE",
    "FALSE",
    null,
    null
  ],
  [
    "Aveanna",
    "898183fe2763549b",
    "11/16",
    "Group-5f97",
    "JOB-994276",
    "Sarah Anderson",
    "sarah.anderson50@gmail.com",
    "+19392959178",
    "Dallas, OH",
    "LPN/LVN",
    "https://drive.google.com/file/d/926b18de9b28e3936afe/view?usp=drive_link",
    "Texas",
    "Dallas, OH",
    null,
    "Yes",
    null,
    "Nitin",
    "ZipOrg",
    "Average",
    "Yes",
    "No Match",
    null,
    "Skills",
    "Notes for candidate 10",
    "No",
    null,
    "TRUE",
    "TRUE",
    "FALSE",
    "FALSE",
    "Email",
    null
  ],
  [
    "Aveanna",
    "462a2260251953e2",
    "11/17",
    "Group-6519",
    "JOB-70c94a",
    "Jennifer Gonzalez",
    "jennifer.gonzalez31@gmail.com",
    "+19913198424",
    "El Paso, PA",
    "LPN/LVN",
    "https://drive.google.com/file/d/31bdc8ebb4fda3535863/view?usp=drive_link",
    "Texas",
    "El Paso, PA",
    "Interview",
    "Yes",
    null,
    "Shivam",
    "ZipOrg",
    "Good",
    "Yes",
    "No Match",
    "Yes",
    "Skills",
    "Notes for candidate 11",
    "No",
    "Jgonzalez@outlook.com",
    "FALSE",
    "TRUE",
    "FALSE",
    "TRUE",
    null,
    null
  ],
  [
    "Aveanna",
    "1a803b50f69fa127",
    "11/18",
    "Group-3cc1",
    "JOB-d062b1",
    "Daniel Gonzalez",
    "daniel.gonzalez81@gmail.com",
    "+11218893623",
    "San Antonio, IL",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/e2039104b123d7a1b7df/view?usp=drive_link",
    "Texas",
    "San Antonio, IL",
    "Pending",
    null,
    "Yes",
    "Ishan",
    "Manatal",
    "Average",
    null,
    "No Match",
    null,
    "Skills",
    "Notes for candidate 12",
    "No",
    null,
    "TRUE",
    "FALSE",
    "TRUE",
    "FALSE",
    "SMS",
    "Failed"
  ],
  [
    "Aveanna",
    "d60fcbde68157699",
    "11/19",
    "Group-cd30",
    "JOB-70ce8a",
    "Daniel Davis",
    "daniel.davis50@gmail.com",
    "+19586343116",
    "Dallas, CA",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/889fe11e9f9735c6d6e0/view?usp=drive_link",
    "Texas",
    "Dallas, CA",
    "Submitted",
    "Yes",
    "No",
    "Nitin",
    "Indeed",
    "Bad",
    "Yes",
    "Match",
    "Yes",
    "Experience",
    "Notes for candidate 13",
    "Yes",
    "Ddavis@outlook.com",
    "TRUE",
    "FALSE",
    "TRUE",
    "TRUE",
    null,
    "Success"
  ],
  [
    "Aveanna",
    "ca2007dbd4385d1a",
    "11/20",
    "Group-3368",
    "JOB-8e8739",
    "Christopher Davis",
    "christopher.davis74@gmail.com",
    "+18972518846",
    "Laredo, TX",
    "Registered Nurse",
    "https://drive.google.com/file/d/745e22b680049b9fc133/view?usp=drive_link",
    "Texas",
    "Laredo, TX",
    "Pending",
    "No",
    "Yes",
    "Nitin",
    "ZipOrg",
    "Average",
    "No",
    "Match",
    "No",
    "Location",
    "Notes for candidate 14",
    "Yes",
    "Cdavis@outlook.com",
    "FALSE",
    "TRUE",
    "TRUE",
    "FALSE",
    "Email",
    null
  ],
  [
    "Aveanna",
    "b8232c3fa639012f",
    "11/21",
    "Group-9961",
    "JOB-6bf6d0",
    "Jessica Anderson",
    "jessica.anderson77@gmail.com",
    "+11275510967",
    "Laredo, NY",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/cfb5c9b93ad85be11ab1/view?usp=drive_link",
    "Texas",
    "Laredo, NY",
    "Pending",
    "No",
    "Yes",
    "Shivam",
    "Indeed",
    "Good",
    "No",
    "No Match",
    "No",
    "Experience",
    "Notes for candidate 15",
    "Yes",
    "Janderson@outlook.com",
    "FALSE",
    "FALSE",
    "FALSE",
    "TRUE",
    null,
    "Success"
  ],
  [
    "Aveanna",
    "4a5c35a2b158879d",
    "11/22",
    "Group-7d13",
    "JOB-4c2e21",
    "William Anderson",
    "william.anderson74@gmail.com",
    "+14176902133",
    "Houston, TX",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/fc386b6be3f5ad028fa3/view?usp=drive_link",
    "Texas",
    "Houston, TX",
    "Rejected",
    "No",
    "Maybe",
    "Shivam",
    "Manatal",
    "Average",
    "No",
    "No Match",
    null,
    "Experience",
    "Notes for candidate 16",
    "No",
    null,
    "TRUE",
    "TRUE",
    "TRUE",
    "TRUE",
    "SMS",
    "Success"
  ],
  [
    "Aveanna",
    "6fe03b6b5e69d274",
    "11/23",
    "Group-c1d5",
    "JOB-4842bf",
    "Elizabeth Wilson",
    "elizabeth.wilson26@gmail.com",
    "+16472277024",
    "Spring, PA",
    "LPN/LVN",
    "https://drive.google.com/file/d/f212e5beca295bf0f978/view?usp=drive_link",
    "Texas",
    "Spring, PA",
    "Pending",
    null,
    "Maybe",
    "Nitin",
    "ZipSp",
    "Bad",
    "Yes",
    "No Match",
    "No",
    "Skills",
    "Notes for candidate 17",
    "No",
    "Ewilson@outlook.com",
    "FALSE",
    "FALSE",
    "FALSE",
    "TRUE",
    "Email",
    null
  ],
  [
    "Aveanna",
    "d00c13a31149295e",
    "11/24",
    "Group-c699",
    "JOB-a71323",
    "Michael Thomas",
    "michael.thomas79@gmail.com",
    "+11651513964",
    "Fort Worth, OH",
    "LPN/LVN",
    "https://drive.google.com/file/d/42064bd3e4aca0abd3ce/view?usp=drive_link",
    "Texas",
    "Fort Worth, OH",
    "Pending",
    null,
    "Yes",
    "Shivam",
    "ZipOrg",
    "Average",
    null,
    "No Match",
    "Yes",
    null,
    "Notes for candidate 18",
    "No",
    null,
    "FALSE",
    "FALSE",
    "FALSE",
    "TRUE",
    "SMS",
    "Success"
  ],
  [
    "Aveanna",
    "e2a9c9d9d83efc4d",
    "11/25",
    "Group-c25f",
    "JOB-752444",
    "James Williams",
    "james.williams65@gmail.com",
    "+16629373800",
    "Spring, OH",
    "LPN/LVN",
    "https://drive.google.com/file/d/17efc7ef08da23f37e59/view?usp=drive_link",
    "Texas",
    "Spring, OH",
    null,
    "Yes",
    "Maybe",
    "Vaishnavi",
    "Indeed",
    "Good",
    null,
    "Match",
    null,
    null,
    "Notes for candidate 19",
    "No",
    null,
    "TRUE",
    "TRUE",
    "FALSE",
    "TRUE",
    null,
    "Success"
  ],
  [
    "Aveanna",
    "135785cfcf81145c",
    "11/26",
    "Group-4668",
    "JOB-df030d",
    "Christopher Smith",
    "christopher.smith58@gmail.com",
    "+11115907764",
    "Arlington, NY",
    "Registered Nurse",
    "https://drive.google.com/file/d/9fb5bb9db8c33155121f/view?usp=drive_link",
    "Texas",
    "Arlington, NY",
    "Submitted",
    null,
    "Yes",
    "Shivam",
    "ZipSp",
    "Bad",
    "No",
    "Match",
    "No",
    "Experience",
    "Notes for candidate 20",
    "Yes",
    null,
    "FALSE",
    "FALSE",
    "FALSE",
    "FALSE",
    null,
    "Failed"
  ],
  [
    "Aveanna",
    "c2a4446f3cf41735",
    "11/27",
    "Group-2d7c",
    "JOB-3638f9",
    "Joseph Lopez",
    "joseph.lopez63@gmail.com",
    "+14866587760",
    "Houston, CA",
    "LPN/LVN",
    "https://drive.google.com/file/d/3e80a0d38b2cee998a6f/view?usp=drive_link",
    "Texas",
    "Houston, CA",
    "Submitted",
    null,
    null,
    "Vaishnavi",
    "Manatal",
    "Good",
    null,
    "Match",
    "Yes",
    null,
    "Notes for candidate 21",
    "No",
    null,
    "TRUE",
    "TRUE",
    "FALSE",
    "FALSE",
    "SMS",
    "Failed"
  ],
  [
    "Aveanna",
    "4e6f0a5cdab2ec24",
    "11/28",
    "Group-2bd4",
    "JOB-63bdc3",
    "Michael Brown",
    "michael.brown48@gmail.com",
    "+15982497706",
    "Dallas, OH",
    "LPN/LVN",
    "https://drive.google.com/file/d/c58ce6cc81e97c676990/view?usp=drive_link",
    "Texas",
    "Dallas, OH",
    null,
    "Yes",
    "Maybe",
    "Vaishnavi",
    "Indeed",
    "Average",
    null,
    "Match",
    null,
    null,
    "Notes for candidate 22",
    "Yes",
    "Mbrown@outlook.com",
    "TRUE",
    "TRUE",
    "FALSE",
    "TRUE",
    null,
    "Failed"
  ],
  [
    "Aveanna",
    "759bcb6a82438588",
    "11/29",
    "Group-9397",
    "JOB-f76928",
    "David Miller",
    "david.miller34@gmail.com",
    "+18623020285",
    "Dallas, IL",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/fe4f414bd7e121eb9304/view?usp=drive_link",
    "Texas",
    "Dallas, IL",
    null,
    null,
    "Yes",
    "Nitin",
    "Manatal",
    "Bad",
    null,
    "Match",
    "No",
    "Skills",
    "Notes for candidate 23",
    "No",
    null,
    "FALSE",
    "TRUE",
    "TRUE",
    "TRUE",
    "Email",
    "Success"
  ],
  [
    "Aveanna",
    "b7e891fb9a0b2a73",
    "11/30",
    "Group-d77a",
    "JOB-932e77",
    "Jessica Garcia",
    "jessica.garcia55@gmail.com",
    "+11955873915",
    "San Antonio, NC",
    "Registered Nurse",
    "https://drive.google.com/file/d/93a8d542c744129fc388/view?usp=drive_link",
    "Texas",
    "San Antonio, NC",
    null,
    null,
    null,
    "Shivam",
    "ZipSp",
    "Bad",
    "Yes",
    "No Match",
    "No",
    null,
    "Notes for candidate 24",
    "Yes",
    null,
    "TRUE",
    "FALSE",
    "TRUE",
    "FALSE",
    "SMS",
    "Failed"
  ],
  [
    "Aveanna",
    "c2a5184f08033dc8",
    "12/1",
    "Group-7b42",
    "JOB-13cd93",
    "James Taylor",
    "james.taylor16@gmail.com",
    "+19847979202",
    "San Antonio, MI",
    "LPN/LVN",
    "https://drive.google.com/file/d/3152a9d956b15c8a2882/view?usp=drive_link",
    "Texas",
    "San Antonio, MI",
    "Submitted",
    null,
    "No",
    "Vaishnavi",
    "Manatal",
    "Bad",
    "No",
    "Match",
    "Yes",
    "Location",
    "Notes for candidate 25",
    "Yes",
    null,
    "FALSE",
    "TRUE",
    "FALSE",
    "FALSE",
    null,
    "Failed"
  ],
  [
    "Aveanna",
    "a5f70545b7076c35",
    "12/2",
    "Group-de4f",
    "JOB-5f848c",
    "Elizabeth Martinez",
    "elizabeth.martinez76@gmail.com",
    "+12402572594",
    "Arlington, NY",
    "LPN/LVN",
    "https://drive.google.com/file/d/8a5db05b14add406c999/view?usp=drive_link",
    "Texas",
    "Arlington, NY",
    "Rejected",
    null,
    null,
    "Vaishnavi",
    "ZipOrg",
    "Bad",
    "Yes",
    "Match",
    null,
    null,
    "Notes for candidate 26",
    "No",
    null,
    "FALSE",
    "TRUE",
    "TRUE",
    "FALSE",
    "Email",
    null
  ],
  [
    "Aveanna",
    "1db64c1b52a4ba33",
    "12/3",
    "Group-2f6c",
    "JOB-cb670a",
    "Susan Rodriguez",
    "susan.rodriguez68@gmail.com",
    "+19528346795",
    "Plano, CA",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/b0d906ee1857747ceac5/view?usp=drive_link",
    "Texas",
    "Plano, CA",
    "Interview",
    "No",
    "No",
    "Nitin",
    "Manatal",
    "Average",
    null,
    "No Match",
    "Yes",
    "Skills",
    "Notes for candidate 27",
    "No",
    "Srodriguez@outlook.com",
    "FALSE",
    "TRUE",
    "TRUE",
    "TRUE",
    null,
    null
  ],
  [
    "Aveanna",
    "7db5a303845a0de2",
    "12/4",
    "Group-9080",
    "JOB-2d1241",
    "Michael Hernandez",
    "michael.hernandez94@gmail.com",
    "+19924152156",
    "Laredo, MI",
    "Registered Nurse",
    "https://drive.google.com/file/d/c12d29d1dfe1b9189a92/view?usp=drive_link",
    "Texas",
    "Laredo, MI",
    "Submitted",
    "No",
    "Maybe",
    "Nitin",
    "Manatal",
    "Average",
    "No",
    "Match",
    null,
    "Skills",
    "Notes for candidate 28",
    "Yes",
    "Mhernandez@outlook.com",
    "TRUE",
    "FALSE",
    "TRUE",
    "FALSE",
    "SMS",
    "Failed"
  ],
  [
    "Aveanna",
    "f19bfc478ba53df6",
    "12/5",
    "Group-3b81",
    "JOB-2acb3c",
    "Robert Garcia",
    "robert.garcia99@gmail.com",
    "+13221830118",
    "Laredo, GA",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/a42134790adc502a9c3b/view?usp=drive_link",
    "Texas",
    "Laredo, GA",
    "Interview",
    null,
    "Maybe",
    "Nitin",
    "ZipSp",
    "Good",
    null,
    "Match",
    "No",
    "Experience",
    "Notes for candidate 29",
    "Yes",
    "Rgarcia@outlook.com",
    "FALSE",
    "TRUE",
    "FALSE",
    "TRUE",
    "Email",
    "Failed"
  ],
  [
    "Aveanna",
    "19557d9e36a41641",
    "12/6",
    "Group-b8f6",
    "JOB-15a7d2",
    "Elizabeth Moore",
    "elizabeth.moore97@gmail.com",
    "+16498863632",
    "Spring, NY",
    "LPN/LVN",
    "https://drive.google.com/file/d/bbee56f94fbe42cba07f/view?usp=drive_link",
    "Texas",
    "Spring, NY",
    null,
    "No",
    "No",
    "Nitin",
    "Indeed",
    "Good",
    null,
    "No Match",
    null,
    "Skills",
    "Notes for candidate 30",
    "Yes",
    null,
    "FALSE",
    "TRUE",
    "FALSE",
    "TRUE",
    null,
    null
  ],
  [
    "Aveanna",
    "0f36f783cdd8fe31",
    "12/7",
    "Group-2a49",
    "JOB-89b824",
    "Robert Jones",
    "robert.jones52@gmail.com",
    "+12145471960",
    "Fort Worth, CA",
    "LPN/LVN",
    "https://drive.google.com/file/d/6edfcca103310cbe3671/view?usp=drive_link",
    "Texas",
    "Fort Worth, CA",
    "Submitted",
    "Yes",
    "Yes",
    "Vaishnavi",
    "Indeed",
    "Good",
    "Yes",
    "No Match",
    "No",
    "Location",
    "Notes for candidate 31",
    "No",
    "Rjones@outlook.com",
    "TRUE",
    "TRUE",
    "FALSE",
    "FALSE",
    "Email",
    null
  ],
  [
    "Aveanna",
    "f1f124aa95991cbc",
    "12/8",
    "Group-861b",
    "JOB-32d6de",
    "Jennifer Hernandez",
    "jennifer.hernandez65@gmail.com",
    "+12513765913",
    "Spring, NY",
    "Registered Nurse",
    "https://drive.google.com/file/d/1f38bf58b0f77077c435/view?usp=drive_link",
    "Texas",
    "Spring, NY",
    "Interview",
    "Yes",
    null,
    "Shivam",
    "ZipOrg",
    "Average",
    "Yes",
    "No Match",
    "Yes",
    "Skills",
    "Notes for candidate 32",
    "Yes",
    "Jhernandez@outlook.com",
    "TRUE",
    "TRUE",
    "TRUE",
    "FALSE",
    "Email",
    "Success"
  ],
  [
    "Aveanna",
    "d64dc518fbc000d5",
    "12/9",
    "Group-2ea7",
    "JOB-95d14d",
    "William Lopez",
    "william.lopez66@gmail.com",
    "+11252348229",
    "Dallas, IL",
    "LPN/LVN",
    "https://drive.google.com/file/d/b92cf3667546a267c72e/view?usp=drive_link",
    "Texas",
    "Dallas, IL",
    "Pending",
    "No",
    "Maybe",
    "Nitin",
    "Indeed",
    "Bad",
    "No",
    "No Match",
    "No",
    "Skills",
    "Notes for candidate 33",
    "Yes",
    null,
    "FALSE",
    "FALSE",
    "TRUE",
    "TRUE",
    null,
    "Failed"
  ],
  [
    "Aveanna",
    "9cbef25a0d759afa",
    "12/10",
    "Group-915b",
    "JOB-62c200",
    "Jennifer Garcia",
    "jennifer.garcia68@gmail.com",
    "+18269778601",
    "Austin, FL",
    "LPN/LVN",
    "https://drive.google.com/file/d/fb7e91d58c59e113decd/view?usp=drive_link",
    "Texas",
    "Austin, FL",
    "Rejected",
    "No",
    null,
    "Ishan",
    "Indeed",
    "Bad",
    "No",
    "Match",
    "Yes",
    "Experience",
    "Notes for candidate 34",
    "No",
    "Jgarcia@outlook.com",
    "TRUE",
    "FALSE",
    "TRUE",
    "TRUE",
    "SMS",
    "Failed"
  ],
  [
    "Aveanna",
    "a095cd0a51104178",
    "12/11",
    "Group-ec53",
    "JOB-117502",
    "Joseph Martinez",
    "joseph.martinez78@gmail.com",
    "+13699477507",
    "Houston, MI",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/e00067591c62e58e2760/view?usp=drive_link",
    "Texas",
    "Houston, MI",
    "Pending",
    "No",
    "Maybe",
    "Shivam",
    "Indeed",
    "Bad",
    "Yes",
    "Match",
    "Yes",
    "Location",
    "Notes for candidate 35",
    "Yes",
    "Jmartinez@outlook.com",
    "TRUE",
    "TRUE",
    "FALSE",
    "FALSE",
    null,
    null
  ],
  [
    "Aveanna",
    "442f7e5694625f62",
    "12/12",
    "Group-3e07",
    "JOB-a4c5d7",
    "Jennifer Brown",
    "jennifer.brown39@gmail.com",
    "+11478960621",
    "Spring, MI",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/8c83ff2577dd52ec7a9e/view?usp=drive_link",
    "Texas",
    "Spring, MI",
    null,
    "Yes",
    "Maybe",
    "Vaishnavi",
    "ZipOrg",
    "Good",
    "No",
    "No Match",
    "No",
    "Experience",
    "Notes for candidate 36",
    "Yes",
    null,
    "TRUE",
    "FALSE",
    "TRUE",
    "FALSE",
    null,
    null
  ],
  [
    "Aveanna",
    "4f99be53dbc1b168",
    "12/13",
    "Group-5c50",
    "JOB-b5be10",
    "William Jackson",
    "william.jackson40@gmail.com",
    "+19477950821",
    "Arlington, FL",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/ca678e7a2672127d3707/view?usp=drive_link",
    "Texas",
    "Arlington, FL",
    null,
    null,
    "Yes",
    "Nitin",
    "ZipOrg",
    "Average",
    null,
    "No Match",
    null,
    "Location",
    "Notes for candidate 37",
    "No",
    "Wjackson@outlook.com",
    "FALSE",
    "FALSE",
    "TRUE",
    "TRUE",
    "SMS",
    "Success"
  ],
  [
    "Aveanna",
    "793e95c41956474c",
    "12/14",
    "Group-9f93",
    "JOB-0cc7f5",
    "Jessica Johnson",
    "jessica.johnson52@gmail.com",
    "+18708115604",
    "El Paso, NC",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/af36a81b15c5c33eb74a/view?usp=drive_link",
    "Texas",
    "El Paso, NC",
    "Submitted",
    null,
    "Maybe",
    "Vaishnavi",
    "ZipSp",
    "Bad",
    "No",
    "Match",
    null,
    null,
    "Notes for candidate 38",
    "No",
    "Jjohnson@outlook.com",
    "FALSE",
    "FALSE",
    "TRUE",
    "FALSE",
    null,
    "Failed"
  ],
  [
    "Aveanna",
    "a1445fe1bfa45ed8",
    "12/15",
    "Group-5cc7",
    "JOB-5339b6",
    "Linda Brown",
    "linda.brown58@gmail.com",
    "+14906989007",
    "Fort Worth, IL",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/dddf9c40257363f36590/view?usp=drive_link",
    "Texas",
    "Fort Worth, IL",
    null,
    "No",
    null,
    "Vaishnavi",
    "ZipOrg",
    "Good",
    "Yes",
    "No Match",
    "No",
    "Location",
    "Notes for candidate 39",
    "Yes",
    "Lbrown@outlook.com",
    "FALSE",
    "TRUE",
    "FALSE",
    "FALSE",
    "Email",
    "Success"
  ],
  [
    "Aveanna",
    "aef1a373de489633",
    "12/16",
    "Group-752a",
    "JOB-9fdb83",
    "David Martin",
    "david.martin37@gmail.com",
    "+14259780751",
    "Houston, PA",
    "LPN/LVN",
    "https://drive.google.com/file/d/ee427efc1b3656932cf0/view?usp=drive_link",
    "Texas",
    "Houston, PA",
    null,
    "Yes",
    "Maybe",
    "Vaishnavi",
    "ZipOrg",
    "Average",
    "Yes",
    "No Match",
    "Yes",
    "Location",
    "Notes for candidate 40",
    "No",
    "Dmartin@outlook.com",
    "TRUE",
    "FALSE",
    "TRUE",
    "FALSE",
    null,
    null
  ],
  [
    "Aveanna",
    "b72efd1d455aa4cc",
    "12/17",
    "Group-13cb",
    "JOB-99837e",
    "Ashley Davis",
    "ashley.davis13@gmail.com",
    "+19068298690",
    "Fort Worth, OH",
    "Registered Nurse",
    "https://drive.google.com/file/d/6a049871d6db83a0212a/view?usp=drive_link",
    "Texas",
    "Fort Worth, OH",
    "Rejected",
    "No",
    "Yes",
    "Shivam",
    "ZipSp",
    "Bad",
    null,
    "No Match",
    null,
    "Experience",
    "Notes for candidate 41",
    "Yes",
    null,
    "TRUE",
    "FALSE",
    "FALSE",
    "TRUE",
    "SMS",
    "Failed"
  ],
  [
    "Aveanna",
    "55ea8c3adf880f00",
    "12/18",
    "Group-7b28",
    "JOB-3da2ac",
    "Elizabeth Wilson",
    "elizabeth.wilson73@gmail.com",
    "+15770716309",
    "Arlington, PA",
    "LPN/LVN",
    "https://drive.google.com/file/d/c8a662b612adfd92efe4/view?usp=drive_link",
    "Texas",
    "Arlington, PA",
    "Pending",
    "Yes",
    "Maybe",
    "Shivam",
    "ZipSp",
    "Bad",
    null,
    "Match",
    "Yes",
    "Skills",
    "Notes for candidate 42",
    "No",
    null,
    "TRUE",
    "TRUE",
    "FALSE",
    "TRUE",
    "Email",
    "Failed"
  ],
  [
    "Aveanna",
    "5ba09e4597229c1d",
    "12/19",
    "Group-ae6e",
    "JOB-6bd1dd",
    "Jennifer Jones",
    "jennifer.jones96@gmail.com",
    "+13064067328",
    "El Paso, GA",
    "Registered Nurse",
    "https://drive.google.com/file/d/abb1e873e8d1d0e7fdaf/view?usp=drive_link",
    "Texas",
    "El Paso, GA",
    "Pending",
    null,
    null,
    "Shivam",
    "Indeed",
    "Average",
    null,
    "No Match",
    "Yes",
    null,
    "Notes for candidate 43",
    "No",
    "Jjones@outlook.com",
    "FALSE",
    "TRUE",
    "TRUE",
    "FALSE",
    null,
    "Success"
  ],
  [
    "Aveanna",
    "ce4804e743677a5a",
    "12/20",
    "Group-07af",
    "JOB-450e68",
    "Linda Wilson",
    "linda.wilson34@gmail.com",
    "+17140209769",
    "Plano, CA",
    "Registered Nurse",
    "https://drive.google.com/file/d/a0d6d4442e968b8a0b35/view?usp=drive_link",
    "Texas",
    "Plano, CA",
    "Pending",
    "Yes",
    "No",
    "Shivam",
    "ZipSp",
    "Bad",
    "Yes",
    "No Match",
    "Yes",
    null,
    "Notes for candidate 44",
    "Yes",
    "Lwilson@outlook.com",
    "TRUE",
    "TRUE",
    "FALSE",
    "FALSE",
    null,
    null
  ],
  [
    "Aveanna",
    "690cacb6a5bd2f0a",
    "12/21",
    "Group-3d98",
    "JOB-055ed1",
    "Jennifer Moore",
    "jennifer.moore21@gmail.com",
    "+14505477331",
    "San Antonio, NY",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/8ed4b6dcd12f2da83f30/view?usp=drive_link",
    "Texas",
    "San Antonio, NY",
    null,
    "Yes",
    "Maybe",
    "Nitin",
    "ZipSp",
    "Average",
    "Yes",
    "Match",
    "Yes",
    null,
    "Notes for candidate 45",
    "No",
    null,
    "TRUE",
    "TRUE",
    "TRUE",
    "TRUE",
    "Email",
    "Failed"
  ],
  [
    "Aveanna",
    "3afd18227e3ee5be",
    "12/22",
    "Group-207a",
    "JOB-0bb587",
    "Jennifer Lopez",
    "jennifer.lopez36@gmail.com",
    "+11898574271",
    "San Antonio, IL",
    "Registered Nurse",
    "https://drive.google.com/file/d/ceed9065cef5625dd980/view?usp=drive_link",
    "Texas",
    "San Antonio, IL",
    "Submitted",
    "No",
    null,
    "Ishan",
    "Indeed",
    "Bad",
    "No",
    "Match",
    "Yes",
    "Skills",
    "Notes for candidate 46",
    "Yes",
    "Jlopez@outlook.com",
    "FALSE",
    "TRUE",
    "TRUE",
    "FALSE",
    "Email",
    "Success"
  ],
  [
    "Aveanna",
    "6d6d754065de0b46",
    "12/23",
    "Group-e079",
    "JOB-1ebef0",
    "Michael Gonzalez",
    "michael.gonzalez17@gmail.com",
    "+15558054259",
    "Austin, IL",
    "Registered Nurse",
    "https://drive.google.com/file/d/f23ef228d2236de851b6/view?usp=drive_link",
    "Texas",
    "Austin, IL",
    null,
    "No",
    null,
    "Vaishnavi",
    "ZipOrg",
    "Good",
    null,
    "No Match",
    "No",
    "Location",
    "Notes for candidate 47",
    "No",
    null,
    "TRUE",
    "FALSE",
    "TRUE",
    "FALSE",
    "Email",
    "Success"
  ],
  [
    "Aveanna",
    "5eae58d45488eb6a",
    "12/24",
    "Group-7b8f",
    "JOB-426ce1",
    "Daniel Gonzalez",
    "daniel.gonzalez83@gmail.com",
    "+17831809743",
    "El Paso, IL",
    "LPN/LVN",
    "https://drive.google.com/file/d/3865a2555cde29d147fe/view?usp=drive_link",
    "Texas",
    "El Paso, IL",
    "Submitted",
    null,
    "Yes",
    "Vaishnavi",
    "Indeed",
    "Bad",
    "Yes",
    "No Match",
    "No",
    "Location",
    "Notes for candidate 48",
    "No",
    "Dgonzalez@outlook.com",
    "FALSE",
    "TRUE",
    "TRUE",
    "TRUE",
    "SMS",
    null
  ],
  [
    "Aveanna",
    "260fc3278f16fd1d",
    "12/25",
    "Group-1002",
    "JOB-130662",
    "Susan Garcia",
    "susan.garcia28@gmail.com",
    "+11343795153",
    "Plano, GA",
    "Registered Nurse",
    "https://drive.google.com/file/d/ddf5b3b6e612aaf71525/view?usp=drive_link",
    "Texas",
    "Plano, GA",
    "Rejected",
    "No",
    "Maybe",
    "Ishan",
    "ZipSp",
    "Bad",
    "Yes",
    "Match",
    null,
    "Skills",
    "Notes for candidate 49",
    "Yes",
    "Sgarcia@outlook.com",
    "TRUE",
    "TRUE",
    "TRUE",
    "FALSE",
    null,
    "Failed"
  ],
  [
    "Aveanna",
    "ca95240e2ff18d36",
    "12/26",
    "Group-394e",
    "JOB-60891f",
    "William Gonzalez",
    "william.gonzalez98@gmail.com",
    "+15927096079",
    "Laredo, NY",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/7e5909af34fc74ba7dde/view?usp=drive_link",
    "Texas",
    "Laredo, NY",
    "Interview",
    "Yes",
    "Yes",
    "Shivam",
    "ZipSp",
    "Bad",
    "No",
    "Match",
    "No",
    "Location",
    "Notes for candidate 50",
    "Yes",
    null,
    "FALSE",
    "FALSE",
    "FALSE",
    "FALSE",
    null,
    null
  ],
  [
    "Aveanna",
    "7909f982977c87d5",
    "12/27",
    "Group-11a6",
    "JOB-2a2cab",
    "Jessica Lopez",
    "jessica.lopez57@gmail.com",
    "+16207227232",
    "Austin, FL",
    "LPN/LVN",
    "https://drive.google.com/file/d/d826ee8c81b1d52652f1/view?usp=drive_link",
    "Texas",
    "Austin, FL",
    null,
    "No",
    "No",
    "Nitin",
    "Indeed",
    "Average",
    null,
    "No Match",
    "Yes",
    "Experience",
    "Notes for candidate 51",
    "No",
    "Jlopez@outlook.com",
    "FALSE",
    "TRUE",
    "TRUE",
    "FALSE",
    "SMS",
    "Failed"
  ],
  [
    "Aveanna",
    "319b24814998bc90",
    "12/28",
    "Group-cd8b",
    "JOB-4e900c",
    "James Miller",
    "james.miller46@gmail.com",
    "+19176896734",
    "San Antonio, GA",
    "LPN/LVN",
    "https://drive.google.com/file/d/55a84316411b3f80d55d/view?usp=drive_link",
    "Texas",
    "San Antonio, GA",
    "Rejected",
    null,
    null,
    "Ishan",
    "Indeed",
    "Average",
    "Yes",
    "Match",
    "Yes",
    null,
    "Notes for candidate 52",
    "Yes",
    null,
    "FALSE",
    "FALSE",
    "TRUE",
    "TRUE",
    "Email",
    null
  ],
  [
    "Aveanna",
    "87972a250a4aef67",
    "12/29",
    "Group-c9fe",
    "JOB-71b867",
    "Margaret Lopez",
    "margaret.lopez70@gmail.com",
    "+17973206850",
    "Fort Worth, PA",
    "Registered Nurse",
    "https://drive.google.com/file/d/7f8fcf5dc4a4c24af960/view?usp=drive_link",
    "Texas",
    "Fort Worth, PA",
    null,
    null,
    "No",
    "Shivam",
    "ZipSp",
    "Average",
    "Yes",
    "Match",
    null,
    null,
    "Notes for candidate 53",
    "No",
    null,
    "FALSE",
    "TRUE",
    "FALSE",
    "TRUE",
    null,
    "Failed"
  ],
  [
    "Aveanna",
    "83a7b6b1468e7f67",
    "12/30",
    "Group-7873",
    "JOB-da09f5",
    "Jennifer Moore",
    "jennifer.moore16@gmail.com",
    "+19138849209",
    "Fort Worth, IL",
    "Registered Nurse",
    "https://drive.google.com/file/d/367e8f81a20562db4a1e/view?usp=drive_link",
    "Texas",
    "Fort Worth, IL",
    "Interview",
    "No",
    "Maybe",
    "Shivam",
    "ZipOrg",
    "Bad",
    null,
    "Match",
    "Yes",
    "Experience",
    "Notes for candidate 54",
    "Yes",
    null,
    "TRUE",
    "FALSE",
    "TRUE",
    "FALSE",
    "SMS",
    "Failed"
  ],
  [
    "Aveanna",
    "9000296f2e6ac14d",
    "12/31",
    "Group-683f",
    "JOB-3e3346",
    "Elizabeth Wilson",
    "elizabeth.wilson24@gmail.com",
    "+18731702403",
    "San Antonio, CA",
    "LPN/LVN",
    "https://drive.google.com/file/d/1f1909cd20d901ca2f44/view?usp=drive_link",
    "Texas",
    "San Antonio, CA",
    "Submitted",
    "No",
    null,
    "Shivam",
    "ZipSp",
    "Good",
    null,
    "No Match",
    "No",
    "Experience",
    "Notes for candidate 55",
    "No",
    null,
    "TRUE",
    "FALSE",
    "TRUE",
    "FALSE",
    null,
    "Failed"
  ],
  [
    "Aveanna",
    "deb881d6c706fa5f",
    "1/1",
    "Group-2a89",
    "JOB-894ee6",
    "Sarah Thomas",
    "sarah.thomas86@gmail.com",
    "+15453970034",
    "Fort Worth, MI",
    "Registered Nurse",
    "https://drive.google.com/file/d/2e8f44dc7720f0a9a6a8/view?usp=drive_link",
    "Texas",
    "Fort Worth, MI",
    null,
    "Yes",
    "No",
    "Ishan",
    "Indeed",
    "Bad",
    "No",
    "No Match",
    "No",
    "Location",
    "Notes for candidate 56",
    "No",
    null,
    "FALSE",
    "FALSE",
    "TRUE",
    "FALSE",
    "Email",
    "Success"
  ],
  [
    "Aveanna",
    "57fa1688d2926c51",
    "1/2",
    "Group-7a2c",
    "JOB-0e21d4",
    "Jennifer Thomas",
    "jennifer.thomas97@gmail.com",
    "+12711804726",
    "Laredo, FL",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/13f76c63cdf5ce311f41/view?usp=drive_link",
    "Texas",
    "Laredo, FL",
    "Pending",
    null,
    "Yes",
    "Ishan",
    "Indeed",
    "Average",
    null,
    "No Match",
    null,
    null,
    "Notes for candidate 57",
    "Yes",
    null,
    "FALSE",
    "FALSE",
    "FALSE",
    "TRUE",
    null,
    "Failed"
  ],
  [
    "Aveanna",
    "20e3fd80a3283065",
    "1/3",
    "Group-22ad",
    "JOB-3466e4",
    "Christopher Miller",
    "christopher.miller52@gmail.com",
    "+17866740906",
    "Plano, CA",
    "LPN/LVN",
    "https://drive.google.com/file/d/6910dd6544375a24bc4d/view?usp=drive_link",
    "Texas",
    "Plano, CA",
    "Submitted",
    "Yes",
    "Maybe",
    "Ishan",
    "Indeed",
    "Good",
    null,
    "No Match",
    null,
    null,
    "Notes for candidate 58",
    "Yes",
    null,
    "FALSE",
    "FALSE",
    "TRUE",
    "TRUE",
    "Email",
    "Failed"
  ],
  [
    "Aveanna",
    "222e4110a188c4fb",
    "1/4",
    "Group-2164",
    "JOB-5269ef",
    "William Wilson",
    "william.wilson45@gmail.com",
    "+13676343943",
    "Dallas, NY",
    "LPN/LVN",
    "https://drive.google.com/file/d/e79ee8e2ae39c5110f97/view?usp=drive_link",
    "Texas",
    "Dallas, NY",
    null,
    "Yes",
    null,
    "Shivam",
    "Manatal",
    "Bad",
    "Yes",
    "No Match",
    null,
    null,
    "Notes for candidate 59",
    "No",
    null,
    "TRUE",
    "FALSE",
    "FALSE",
    "FALSE",
    "Email",
    "Failed"
  ],
  [
    "Aveanna",
    "e1d34fae6da6f249",
    "1/5",
    "Group-82ae",
    "JOB-7d4f2c",
    "Barbara Martin",
    "barbara.martin51@gmail.com",
    "+15418882049",
    "Dallas, IL",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/af5046de68398e8412ce/view?usp=drive_link",
    "Texas",
    "Dallas, IL",
    "Pending",
    null,
    null,
    "Vaishnavi",
    "ZipOrg",
    "Bad",
    null,
    "Match",
    "Yes",
    "Experience",
    "Notes for candidate 60",
    "Yes",
    "Bmartin@outlook.com",
    "TRUE",
    "FALSE",
    "FALSE",
    "FALSE",
    null,
    "Failed"
  ],
  [
    "Aveanna",
    "487f56e8cdd58ad4",
    "1/6",
    "Group-4001",
    "JOB-d31053",
    "Linda Smith",
    "linda.smith45@gmail.com",
    "+11710221568",
    "Austin, IL",
    "LPN/LVN",
    "https://drive.google.com/file/d/47da748b7b715512b411/view?usp=drive_link",
    "Texas",
    "Austin, IL",
    null,
    "No",
    "Maybe",
    "Shivam",
    "Indeed",
    "Average",
    null,
    "Match",
    "No",
    "Experience",
    "Notes for candidate 61",
    "No",
    null,
    "FALSE",
    "FALSE",
    "TRUE",
    "TRUE",
    null,
    null
  ],
  [
    "Aveanna",
    "2ea5eb3a3de27206",
    "1/7",
    "Group-d3c1",
    "JOB-5fac61",
    "Daniel Lopez",
    "daniel.lopez12@gmail.com",
    "+15601989365",
    "Dallas, OH",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/aac7fa3e5e00ea177c89/view?usp=drive_link",
    "Texas",
    "Dallas, OH",
    null,
    null,
    "No",
    "Nitin",
    "ZipOrg",
    "Average",
    "Yes",
    "No Match",
    "No",
    "Experience",
    "Notes for candidate 62",
    "Yes",
    "Dlopez@outlook.com",
    "FALSE",
    "TRUE",
    "TRUE",
    "FALSE",
    "Email",
    "Failed"
  ],
  [
    "Aveanna",
    "8dfa9432e3ed9f76",
    "1/8",
    "Group-9771",
    "JOB-b3d519",
    "Joseph Thomas",
    "joseph.thomas36@gmail.com",
    "+12108519021",
    "Arlington, CA",
    "LPN/LVN",
    "https://drive.google.com/file/d/06a295b3d1b1d30b3c7f/view?usp=drive_link",
    "Texas",
    "Arlington, CA",
    "Pending",
    null,
    "Yes",
    "Nitin",
    "ZipSp",
    "Bad",
    "No",
    "Match",
    "No",
    "Skills",
    "Notes for candidate 63",
    "Yes",
    "Jthomas@outlook.com",
    "TRUE",
    "FALSE",
    "FALSE",
    "FALSE",
    "SMS",
    "Success"
  ],
  [
    "Aveanna",
    "bd7034ee14bcf79c",
    "1/9",
    "Group-9f24",
    "JOB-a802a4",
    "John Wilson",
    "john.wilson33@gmail.com",
    "+16105190523",
    "Houston, GA",
    "LPN/LVN",
    "https://drive.google.com/file/d/197d35bfac59888ec1f1/view?usp=drive_link",
    "Texas",
    "Houston, GA",
    "Rejected",
    "Yes",
    "Maybe",
    "Ishan",
    "ZipSp",
    "Good",
    null,
    "No Match",
    null,
    null,
    "Notes for candidate 64",
    "No",
    null,
    "FALSE",
    "FALSE",
    "FALSE",
    "FALSE",
    "SMS",
    null
  ],
  [
    "Aveanna",
    "cd5d534171100785",
    "1/10",
    "Group-a0f0",
    "JOB-85d29b",
    "John Jones",
    "john.jones45@gmail.com",
    "+19387123600",
    "San Antonio, GA",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/2f20da25d49139b9eaf8/view?usp=drive_link",
    "Texas",
    "San Antonio, GA",
    "Rejected",
    "Yes",
    null,
    "Ishan",
    "Indeed",
    "Good",
    "Yes",
    "No Match",
    null,
    "Experience",
    "Notes for candidate 65",
    "Yes",
    null,
    "FALSE",
    "FALSE",
    "FALSE",
    "FALSE",
    null,
    "Failed"
  ],
  [
    "Aveanna",
    "d4fbe1b9fd5dd83e",
    "1/11",
    "Group-b384",
    "JOB-3c0f73",
    "Ashley Johnson",
    "ashley.johnson82@gmail.com",
    "+19405565237",
    "Austin, PA",
    "LPN/LVN",
    "https://drive.google.com/file/d/d9ba24fcc9f55c70a1ca/view?usp=drive_link",
    "Texas",
    "Austin, PA",
    "Interview",
    "No",
    "Maybe",
    "Ishan",
    "Manatal",
    "Good",
    null,
    "Match",
    null,
    "Skills",
    "Notes for candidate 66",
    "No",
    null,
    "TRUE",
    "TRUE",
    "TRUE",
    "TRUE",
    "SMS",
    "Failed"
  ],
  [
    "Aveanna",
    "82b1aa4242f63bad",
    "1/12",
    "Group-2f9a",
    "JOB-4d2f2f",
    "Charles Jones",
    "charles.jones84@gmail.com",
    "+18161694518",
    "Fort Worth, IL",
    "Registered Nurse",
    "https://drive.google.com/file/d/2f88bb5eadcb7f8cf5a2/view?usp=drive_link",
    "Texas",
    "Fort Worth, IL",
    "Submitted",
    "No",
    "Yes",
    "Nitin",
    "ZipOrg",
    "Bad",
    null,
    "No Match",
    "Yes",
    "Skills",
    "Notes for candidate 67",
    "No",
    "Cjones@outlook.com",
    "TRUE",
    "FALSE",
    "TRUE",
    "FALSE",
    "SMS",
    null
  ],
  [
    "Aveanna",
    "83aa12adb904cead",
    "1/13",
    "Group-fcd7",
    "JOB-b3855e",
    "Margaret Martin",
    "margaret.martin13@gmail.com",
    "+13239749195",
    "San Antonio, TX",
    "LPN/LVN",
    "https://drive.google.com/file/d/5172e16b97cf480ad203/view?usp=drive_link",
    "Texas",
    "San Antonio, TX",
    "Pending",
    "No",
    "No",
    "Ishan",
    "Manatal",
    "Good",
    null,
    "No Match",
    null,
    "Experience",
    "Notes for candidate 68",
    "No",
    "Mmartin@outlook.com",
    "FALSE",
    "TRUE",
    "FALSE",
    "FALSE",
    "SMS",
    null
  ],
  [
    "Aveanna",
    "961008c183e9e3e4",
    "1/14",
    "Group-9140",
    "JOB-cc0e72",
    "Joseph Moore",
    "joseph.moore64@gmail.com",
    "+16034270138",
    "Plano, CA",
    "Registered Nurse",
    "https://drive.google.com/file/d/b704bba246f2b8526cbf/view?usp=drive_link",
    "Texas",
    "Plano, CA",
    "Rejected",
    "Yes",
    null,
    "Shivam",
    "ZipOrg",
    "Good",
    "Yes",
    "No Match",
    "Yes",
    "Location",
    "Notes for candidate 69",
    "No",
    null,
    "FALSE",
    "TRUE",
    "TRUE",
    "TRUE",
    "SMS",
    null
  ],
  [
    "Aveanna",
    "c18772076bf8e028",
    "1/15",
    "Group-145f",
    "JOB-41561a",
    "Charles Williams",
    "charles.williams91@gmail.com",
    "+17425652325",
    "Houston, NY",
    "Registered Nurse",
    "https://drive.google.com/file/d/834992d8b1acebc8d563/view?usp=drive_link",
    "Texas",
    "Houston, NY",
    "Rejected",
    null,
    "No",
    "Nitin",
    "ZipOrg",
    "Good",
    "Yes",
    "Match",
    "No",
    "Skills",
    "Notes for candidate 70",
    "Yes",
    null,
    "FALSE",
    "TRUE",
    "FALSE",
    "FALSE",
    "Email",
    null
  ],
  [
    "Aveanna",
    "ec9be37fa318fb21",
    "1/16",
    "Group-0f9c",
    "JOB-be95a9",
    "Emily Taylor",
    "emily.taylor95@gmail.com",
    "+14845487725",
    "Arlington, NC",
    "Registered Nurse",
    "https://drive.google.com/file/d/ab669427ce868accf0a0/view?usp=drive_link",
    "Texas",
    "Arlington, NC",
    "Rejected",
    "Yes",
    "No",
    "Vaishnavi",
    "ZipSp",
    "Average",
    "No",
    "Match",
    "No",
    "Location",
    "Notes for candidate 71",
    "Yes",
    null,
    "FALSE",
    "TRUE",
    "TRUE",
    "FALSE",
    null,
    "Failed"
  ],
  [
    "Aveanna",
    "e410e27082347fca",
    "1/17",
    "Group-cac0",
    "JOB-0a0b59",
    "William Jones",
    "william.jones68@gmail.com",
    "+13101910899",
    "Houston, IL",
    "Registered Nurse",
    "https://drive.google.com/file/d/a907a967de4511250a5e/view?usp=drive_link",
    "Texas",
    "Houston, IL",
    "Interview",
    null,
    "Maybe",
    "Vaishnavi",
    "Indeed",
    "Bad",
    "Yes",
    "No Match",
    "Yes",
    null,
    "Notes for candidate 72",
    "Yes",
    "Wjones@outlook.com",
    "TRUE",
    "TRUE",
    "TRUE",
    "TRUE",
    null,
    "Failed"
  ],
  [
    "Aveanna",
    "5c069aa8f7b12988",
    "1/18",
    "Group-2073",
    "JOB-71c281",
    "Robert Anderson",
    "robert.anderson33@gmail.com",
    "+15921742096",
    "Plano, NY",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/7629f9976d05a70256ea/view?usp=drive_link",
    "Texas",
    "Plano, NY",
    "Rejected",
    "Yes",
    "Yes",
    "Nitin",
    "ZipSp",
    "Average",
    "Yes",
    "Match",
    null,
    "Experience",
    "Notes for candidate 73",
    "Yes",
    "Randerson@outlook.com",
    "TRUE",
    "FALSE",
    "TRUE",
    "TRUE",
    null,
    null
  ],
  [
    "Aveanna",
    "f6760c1d59d7a508",
    "1/19",
    "Group-b135",
    "JOB-508ac2",
    "Emily Jones",
    "emily.jones54@gmail.com",
    "+19615624517",
    "Austin, TX",
    "Registered Nurse",
    "https://drive.google.com/file/d/a969864957a2a80226d7/view?usp=drive_link",
    "Texas",
    "Austin, TX",
    "Pending",
    "Yes",
    null,
    "Shivam",
    "Manatal",
    "Good",
    "No",
    "Match",
    "Yes",
    "Experience",
    "Notes for candidate 74",
    "No",
    "Ejones@outlook.com",
    "TRUE",
    "FALSE",
    "FALSE",
    "TRUE",
    "Email",
    null
  ],
  [
    "Aveanna",
    "75d5348b80118a1c",
    "1/20",
    "Group-b859",
    "JOB-ca56f6",
    "Jennifer Jackson",
    "jennifer.jackson82@gmail.com",
    "+17855435875",
    "Plano, PA",
    "LPN/LVN",
    "https://drive.google.com/file/d/b9e4837e365bf12f4112/view?usp=drive_link",
    "Texas",
    "Plano, PA",
    "Pending",
    null,
    "Yes",
    "Ishan",
    "Indeed",
    "Average",
    null,
    "No Match",
    "No",
    null,
    "Notes for candidate 75",
    "Yes",
    null,
    "FALSE",
    "TRUE",
    "FALSE",
    "TRUE",
    null,
    "Failed"
  ],
  [
    "Aveanna",
    "877dbe8ef0d0a7d0",
    "1/21",
    "Group-f54b",
    "JOB-175959",
    "Jennifer Davis",
    "jennifer.davis51@gmail.com",
    "+15889513943",
    "Arlington, FL",
    "Registered Nurse",
    "https://drive.google.com/file/d/ea2a0e117310372c3739/view?usp=drive_link",
    "Texas",
    "Arlington, FL",
    "Rejected",
    null,
    null,
    "Vaishnavi",
    "Indeed",
    "Good",
    "No",
    "Match",
    "No",
    "Location",
    "Notes for candidate 76",
    "No",
    null,
    "TRUE",
    "TRUE",
    "TRUE",
    "TRUE",
    null,
    "Failed"
  ],
  [
    "Aveanna",
    "e44f652a74891a92",
    "1/22",
    "Group-238a",
    "JOB-f03256",
    "Charles Jackson",
    "charles.jackson16@gmail.com",
    "+13254757702",
    "Houston, FL",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/f36ef7e2580fe7056b3c/view?usp=drive_link",
    "Texas",
    "Houston, FL",
    null,
    "No",
    "No",
    "Shivam",
    "ZipOrg",
    "Average",
    "No",
    "No Match",
    "Yes",
    "Location",
    "Notes for candidate 77",
    "No",
    "Cjackson@outlook.com",
    "TRUE",
    "TRUE",
    "TRUE",
    "TRUE",
    "Email",
    null
  ],
  [
    "Aveanna",
    "9b0f65f7679be842",
    "1/23",
    "Group-bc80",
    "JOB-e83b2f",
    "Jessica Brown",
    "jessica.brown77@gmail.com",
    "+15110857865",
    "San Antonio, PA",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/9cf308d8de5b7eb8cb18/view?usp=drive_link",
    "Texas",
    "San Antonio, PA",
    "Submitted",
    "Yes",
    "Maybe",
    "Nitin",
    "Manatal",
    "Average",
    null,
    "No Match",
    null,
    "Location",
    "Notes for candidate 78",
    "Yes",
    "Jbrown@outlook.com",
    "TRUE",
    "TRUE",
    "TRUE",
    "TRUE",
    "SMS",
    null
  ],
  [
    "Aveanna",
    "d9f6598e8e170e76",
    "1/24",
    "Group-9bc7",
    "JOB-14e254",
    "Barbara Martinez",
    "barbara.martinez32@gmail.com",
    "+16668792687",
    "Spring, FL",
    "LPN/LVN",
    "https://drive.google.com/file/d/71baef8159d5e66bae36/view?usp=drive_link",
    "Texas",
    "Spring, FL",
    "Rejected",
    null,
    "Yes",
    "Vaishnavi",
    "ZipOrg",
    "Bad",
    "Yes",
    "No Match",
    "No",
    null,
    "Notes for candidate 79",
    "Yes",
    "Bmartinez@outlook.com",
    "FALSE",
    "TRUE",
    "TRUE",
    "TRUE",
    null,
    null
  ],
  [
    "Aveanna",
    "a55d9f2edab0d376",
    "1/25",
    "Group-e179",
    "JOB-05805b",
    "David Lopez",
    "david.lopez16@gmail.com",
    "+11967208860",
    "Arlington, PA",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/eae999cf4f84ead56307/view?usp=drive_link",
    "Texas",
    "Arlington, PA",
    null,
    "Yes",
    "Yes",
    "Nitin",
    "ZipOrg",
    "Good",
    "No",
    "No Match",
    null,
    "Skills",
    "Notes for candidate 80",
    "No",
    null,
    "FALSE",
    "TRUE",
    "TRUE",
    "TRUE",
    "Email",
    null
  ],
  [
    "Aveanna",
    "0374e583af695cfd",
    "1/26",
    "Group-f7f4",
    "JOB-e41572",
    "Michael Wilson",
    "michael.wilson63@gmail.com",
    "+14360583692",
    "Spring, NC",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/3153609de7d4ab451154/view?usp=drive_link",
    "Texas",
    "Spring, NC",
    "Pending",
    null,
    "Maybe",
    "Vaishnavi",
    "Manatal",
    "Average",
    "No",
    "Match",
    null,
    "Skills",
    "Notes for candidate 81",
    "No",
    "Mwilson@outlook.com",
    "TRUE",
    "FALSE",
    "FALSE",
    "TRUE",
    "Email",
    "Failed"
  ],
  [
    "Aveanna",
    "2bbc0676271c6cf6",
    "1/27",
    "Group-f581",
    "JOB-bc2e6a",
    "William Smith",
    "william.smith75@gmail.com",
    "+19851718087",
    "Houston, TX",
    "Registered Nurse",
    "https://drive.google.com/file/d/54738466d46f71431b6c/view?usp=drive_link",
    "Texas",
    "Houston, TX",
    "Rejected",
    null,
    "No",
    "Vaishnavi",
    "ZipOrg",
    "Average",
    "Yes",
    "No Match",
    "No",
    null,
    "Notes for candidate 82",
    "Yes",
    "Wsmith@outlook.com",
    "FALSE",
    "TRUE",
    "TRUE",
    "TRUE",
    "SMS",
    "Success"
  ],
  [
    "Aveanna",
    "3e9624448f9a5b91",
    "1/28",
    "Group-b1a4",
    "JOB-0245ec",
    "William Taylor",
    "william.taylor60@gmail.com",
    "+11759182342",
    "San Antonio, MI",
    "Registered Nurse",
    "https://drive.google.com/file/d/7a365f168fbdf95e3727/view?usp=drive_link",
    "Texas",
    "San Antonio, MI",
    null,
    "No",
    "Yes",
    "Ishan",
    "ZipOrg",
    "Average",
    "No",
    "Match",
    "Yes",
    "Experience",
    "Notes for candidate 83",
    "No",
    null,
    "FALSE",
    "TRUE",
    "FALSE",
    "FALSE",
    "Email",
    "Failed"
  ],
  [
    "Aveanna",
    "edac0e46ebf6fdfb",
    "1/29",
    "Group-8978",
    "JOB-3e69fc",
    "David Martinez",
    "david.martinez58@gmail.com",
    "+18400384076",
    "Houston, GA",
    "LPN/LVN",
    "https://drive.google.com/file/d/c8530abccd0871916fbf/view?usp=drive_link",
    "Texas",
    "Houston, GA",
    "Interview",
    null,
    null,
    "Nitin",
    "Manatal",
    "Bad",
    null,
    "No Match",
    "No",
    null,
    "Notes for candidate 84",
    "No",
    null,
    "FALSE",
    "TRUE",
    "TRUE",
    "FALSE",
    null,
    null
  ],
  [
    "Aveanna",
    "ce537a34c59a688b",
    "1/30",
    "Group-5f89",
    "JOB-cc21f2",
    "Barbara Wilson",
    "barbara.wilson80@gmail.com",
    "+13719704807",
    "San Antonio, OH",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/b58b670913b30862801c/view?usp=drive_link",
    "Texas",
    "San Antonio, OH",
    "Submitted",
    "Yes",
    null,
    "Ishan",
    "ZipSp",
    "Average",
    null,
    "No Match",
    null,
    "Skills",
    "Notes for candidate 85",
    "Yes",
    "Bwilson@outlook.com",
    "TRUE",
    "FALSE",
    "FALSE",
    "TRUE",
    "Email",
    null
  ],
  [
    "Aveanna",
    "b6e733cd34010f13",
    "1/31",
    "Group-7088",
    "JOB-39a9ec",
    "Elizabeth Jackson",
    "elizabeth.jackson21@gmail.com",
    "+18354990450",
    "El Paso, IL",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/64125c7cab7259aea4dc/view?usp=drive_link",
    "Texas",
    "El Paso, IL",
    "Submitted",
    "No",
    "No",
    "Ishan",
    "Manatal",
    "Bad",
    null,
    "Match",
    "Yes",
    null,
    "Notes for candidate 86",
    "No",
    "Ejackson@outlook.com",
    "FALSE",
    "TRUE",
    "TRUE",
    "TRUE",
    "Email",
    "Failed"
  ],
  [
    "Aveanna",
    "118b2d52d5ce4479",
    "2/1",
    "Group-ea6b",
    "JOB-d58610",
    "Christopher Hernandez",
    "christopher.hernandez87@gmail.com",
    "+14882059472",
    "Spring, FL",
    "Registered Nurse",
    "https://drive.google.com/file/d/9c0bbc85f2b909c97282/view?usp=drive_link",
    "Texas",
    "Spring, FL",
    "Rejected",
    null,
    "No",
    "Vaishnavi",
    "ZipOrg",
    "Average",
    null,
    "Match",
    "No",
    "Location",
    "Notes for candidate 87",
    "No",
    null,
    "TRUE",
    "FALSE",
    "TRUE",
    "FALSE",
    null,
    "Success"
  ],
  [
    "Aveanna",
    "fd87ec4edf664112",
    "2/2",
    "Group-1dc8",
    "JOB-f69c55",
    "Barbara Miller",
    "barbara.miller92@gmail.com",
    "+16537524112",
    "Spring, TX",
    "LPN/LVN",
    "https://drive.google.com/file/d/39d31e430e30ca67518b/view?usp=drive_link",
    "Texas",
    "Spring, TX",
    "Interview",
    null,
    null,
    "Ishan",
    "ZipSp",
    "Bad",
    "Yes",
    "No Match",
    null,
    "Location",
    "Notes for candidate 88",
    "No",
    "Bmiller@outlook.com",
    "TRUE",
    "TRUE",
    "TRUE",
    "TRUE",
    "Email",
    "Failed"
  ],
  [
    "Aveanna",
    "53ff1f572fd14160",
    "2/3",
    "Group-c86a",
    "JOB-aa2445",
    "Christopher Smith",
    "christopher.smith43@gmail.com",
    "+15817833791",
    "Dallas, NY",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/3debb484a7f188e0dc7a/view?usp=drive_link",
    "Texas",
    "Dallas, NY",
    "Submitted",
    "Yes",
    "Yes",
    "Shivam",
    "Indeed",
    "Good",
    null,
    "Match",
    "Yes",
    "Location",
    "Notes for candidate 89",
    "No",
    "Csmith@outlook.com",
    "FALSE",
    "FALSE",
    "TRUE",
    "TRUE",
    null,
    null
  ],
  [
    "Aveanna",
    "463e276ec4f33218",
    "2/4",
    "Group-6928",
    "JOB-b4758b",
    "Linda Davis",
    "linda.davis46@gmail.com",
    "+16873485848",
    "Fort Worth, TX",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/fe018532701997f6aefe/view?usp=drive_link",
    "Texas",
    "Fort Worth, TX",
    "Interview",
    null,
    "Maybe",
    "Nitin",
    "ZipSp",
    "Good",
    "Yes",
    "No Match",
    "Yes",
    "Skills",
    "Notes for candidate 90",
    "No",
    "Ldavis@outlook.com",
    "FALSE",
    "TRUE",
    "TRUE",
    "FALSE",
    null,
    "Failed"
  ],
  [
    "Aveanna",
    "6cda0be895bbda13",
    "2/5",
    "Group-5569",
    "JOB-b79e47",
    "Christopher Lopez",
    "christopher.lopez72@gmail.com",
    "+14736388348",
    "Austin, NC",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/7c672dc9d07fee731eed/view?usp=drive_link",
    "Texas",
    "Austin, NC",
    "Submitted",
    "No",
    "Maybe",
    "Ishan",
    "ZipOrg",
    "Average",
    "No",
    "Match",
    "Yes",
    "Experience",
    "Notes for candidate 91",
    "No",
    null,
    "FALSE",
    "TRUE",
    "FALSE",
    "FALSE",
    "SMS",
    null
  ],
  [
    "Aveanna",
    "f551a8dad16e019c",
    "2/6",
    "Group-610f",
    "JOB-96308c",
    "Margaret Gonzalez",
    "margaret.gonzalez41@gmail.com",
    "+13472181324",
    "Houston, CA",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/bb06dc0d5b6fd683f732/view?usp=drive_link",
    "Texas",
    "Houston, CA",
    "Submitted",
    "No",
    "Maybe",
    "Shivam",
    "ZipOrg",
    "Average",
    "No",
    "Match",
    "No",
    "Skills",
    "Notes for candidate 92",
    "Yes",
    null,
    "TRUE",
    "FALSE",
    "TRUE",
    "TRUE",
    "SMS",
    null
  ],
  [
    "Aveanna",
    "2aa48ac3ba81e632",
    "2/7",
    "Group-1465",
    "JOB-5bca28",
    "James Wilson",
    "james.wilson16@gmail.com",
    "+18850077399",
    "Laredo, PA",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/d8f0fee4eee00132e4eb/view?usp=drive_link",
    "Texas",
    "Laredo, PA",
    "Submitted",
    null,
    "No",
    "Ishan",
    "Manatal",
    "Good",
    null,
    "No Match",
    "Yes",
    "Skills",
    "Notes for candidate 93",
    "Yes",
    null,
    "TRUE",
    "TRUE",
    "FALSE",
    "TRUE",
    "Email",
    "Failed"
  ],
  [
    "Aveanna",
    "2dbf2ef69dd3f05b",
    "2/8",
    "Group-85a6",
    "JOB-c921bc",
    "Susan Jones",
    "susan.jones65@gmail.com",
    "+13948292891",
    "Fort Worth, CA",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/6661bc998c5f0bc5b611/view?usp=drive_link",
    "Texas",
    "Fort Worth, CA",
    null,
    "No",
    null,
    "Vaishnavi",
    "Manatal",
    "Good",
    "No",
    "No Match",
    "No",
    "Location",
    "Notes for candidate 94",
    "Yes",
    "Sjones@outlook.com",
    "FALSE",
    "FALSE",
    "FALSE",
    "TRUE",
    "SMS",
    "Success"
  ],
  [
    "Aveanna",
    "e2b894d0df6eff93",
    "2/9",
    "Group-ab99",
    "JOB-531711",
    "Daniel Gonzalez",
    "daniel.gonzalez4@gmail.com",
    "+16752568741",
    "Arlington, FL",
    "Registered Nurse",
    "https://drive.google.com/file/d/16730fba1aa78be75fe2/view?usp=drive_link",
    "Texas",
    "Arlington, FL",
    "Interview",
    "No",
    "No",
    "Ishan",
    "Manatal",
    "Bad",
    "Yes",
    "No Match",
    null,
    "Experience",
    "Notes for candidate 95",
    "No",
    null,
    "FALSE",
    "TRUE",
    "TRUE",
    "TRUE",
    null,
    "Failed"
  ],
  [
    "Aveanna",
    "f72250e6ca372141",
    "2/10",
    "Group-edf3",
    "JOB-48fdf0",
    "Robert Moore",
    "robert.moore71@gmail.com",
    "+15598330270",
    "Austin, NY",
    "Licensed Vocational Nurse (LVN) – Private Duty Nurse",
    "https://drive.google.com/file/d/8bd90862fb804fd09326/view?usp=drive_link",
    "Texas",
    "Austin, NY",
    "Submitted",
    "Yes",
    "No",
    "Vaishnavi",
    "Manatal",
    "Good",
    "No",
    "Match",
    null,
    "Experience",
    "Notes for candidate 96",
    "No",
    "Rmoore@outlook.com",
    "FALSE",
    "FALSE",
    "FALSE",
    "FALSE",
    null,
    null
  ],
  [
    "Aveanna",
    "df75911f02443648",
    "2/11",
    "Group-998e",
    "JOB-f4e663",
    "Sarah Rodriguez",
    "sarah.rodriguez68@gmail.com",
    "+17129776684",
    "Arlington, PA",
    "Registered Nurse",
    "https://drive.google.com/file/d/95821c05c3ad14aa6853/view?usp=drive_link",
    "Texas",
    "Arlington, PA",
    "Pending",
    "Yes",
    null,
    "Vaishnavi",
    "Manatal",
    "Bad",
    null,
    "Match",
    "No",
    null,
    "Notes for candidate 97",
    "No",
    "Srodriguez@outlook.com",
    "TRUE",
    "TRUE",
    "FALSE",
    "TRUE",
    null,
    "Success"
  ],
  [
    "Aveanna",
    "a4c55bc1391099a4",
    "2/12",
    "Group-cca8",
    "JOB-63e621",
    "Charles Miller",
    "charles.miller87@gmail.com",
    "+14823037650",
    "Arlington, OH",
    "LPN/LVN",
    "https://drive.google.com/file/d/889381c18776ed2a3cd8/view?usp=drive_link",
    "Texas",
    "Arlington, OH",
    "Interview",
    "No",
    "Yes",
    "Nitin",
    "Manatal",
    "Average",
    null,
    "Match",
    "Yes",
    "Skills",
    "Notes for candidate 98",
    "Yes",
    null,
    "FALSE",
    "FALSE",
    "FALSE",
    "TRUE",
    "SMS",
    null
  ],
  [
    "Aveanna",
    "9826498b2bea5ef7",
    "2/13",
    "Group-c160",
    "JOB-9c86c8",
    "Charles Hernandez",
    "charles.hernandez10@gmail.com",
    "+13938949063",
    "Spring, TX",
    "Registered Nurse",
    "https://drive.google.com/file/d/356932c6afd5e06519b1/view?usp=drive_link",
    "Texas",
    "Spring, TX",
    "Submitted",
    "Yes",
    "Yes",
    "Vaishnavi",
    "Manatal",
    "Good",
    null,
    "Match",
    "Yes",
    "Experience",
    "Notes for candidate 99",
    "Yes",
    "Chernandez@outlook.com",
    "TRUE",
    "FALSE",
    "FALSE",
    "FALSE",
    "Email",
    "Success"
  ]
];
